### ISSUE TITLE
slack-docker crashes/stops after first container stops or state changes.

### ISSUE THREAD

**Issue by pcross616** [int128/slack-docker#4]
So i am running this as a global container in coreos.  I have been for a while, but recently something changed and now I am getting this error.

Here is my systemd service file for slack-docker

```[Unit]
Description=Docker Monitoring Service

[Service]
TimeoutStartSec=0
ExecStartPre=-/usr/bin/docker kill slack-docker
ExecStartPre=-/usr/bin/docker rm slack-docker
ExecStartPre=/usr/bin/docker pull int128/slack-docker
ExecStart=/usr/bin/bash -c \
"/usr/bin/docker run --rm --name slack-docker -e webhook=https://hooks.slack.com/services/...  \
 -v /var/run/docker.sock:/var/run/docker.sock \
int128/slack-docker"

[X-Fleet]
Global=true
```

When i issue a container stop then say a start this error starts to show up.  I do see the slack-docker catch the stop event and it is published to slack.. but after that just this error with different container Ids.

`Unhandled rejection Error: HTTP code is 404 which indicates error: no such container - no such id: 8aeb404dcb0c823079b4ca17b893c3c6d225f44bcdbdd145a22f3ba46c70a107
Feb 02 03:43:58 ip-172-20-1-56.us-west-2.compute.internal bash[14812]: at /usr/src/app/node_modules/docker-modem/lib/modem.js:229:17
Feb 02 03:43:58 ip-172-20-1-56.us-west-2.compute.internal bash[14812]: at getCause (/usr/src/app/node_modules/docker-modem/lib/modem.js:257:7)
Feb 02 03:43:58 ip-172-20-1-56.us-west-2.compute.internal bash[14812]: at Modem.buildPayload (/usr/src/app/node_modules/docker-modem/lib/modem.js:228:5)
Feb 02 03:43:58 ip-172-20-1-56.us-west-2.compute.internal bash[14812]: at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-modem/lib/modem.js:204:14)
Feb 02 03:43:58 ip-172-20-1-56.us-west-2.compute.internal bash[14812]: at emitNone (events.js:72:20)
Feb 02 03:43:58 ip-172-20-1-56.us-west-2.compute.internal bash[14812]: at IncomingMessage.emit (events.js:166:7)
Feb 02 03:43:58 ip-172-20-1-56.us-west-2.compute.internal bash[14812]: at endReadableNT (_stream_readable.js:905:12)
Feb 02 03:43:58 ip-172-20-1-56.us-west-2.compute.internal bash[14812]: at nextTickCallbackWith2Args (node.js:478:9)
Feb 02 03:43:58 ip-172-20-1-56.us-west-2.compute.internal bash[14812]: at process._tickCallback (node.js:392:17)`

**Comment by israelroldan** [comment]
I am experiencing the same issue. @pcross616 did you find something to prevent this issue?

**Comment by pcross616** [comment]
I have not.

Get Outlook for Android<https://aka.ms/ghei36>




On Tue, Mar 14, 2017 at 6:39 AM -0700, "Israel Roldan" <notifications@github.com<mailto:notifications@github.com>> wrote:


I am experiencing the same issue. @pcross616<https://github.com/pcross616> did you find something to prevent this issue?
